services:
  # テストスクリプトを実行するNode.jsアプリ
  selenium-nodejs:
    container_name: selenium-nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - selenium-hub
      - selenium-chrome
    restart: always
    tty: true
    volumes:
      - ./project:/work

  # Selenium Gridのハブ
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  # VNC機能付きのChromeノード
  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      # VNC接続用のポート
      - "5900:5900"
    shm_size: "4g"
